---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./hr.yaml
configMapGenerator:
  - name: glance-configmap
    files:
      - glance.yml=./config/glance.yaml
      - gatus.yml=./config/gatus.yaml
generatorOptions:
  disableNameSuffixHash: true
