title: Homelab
# background:
#   image: https://raw.githubusercontent.com/joryirving/home-ops/main/.docs/assets/101518784_p0.jpg
#   opacity: 20
favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
theme: dark
color: slate
headerStyle: clean
statusStyle: dot
useEqualHeights: false
fiveColumns: true
target: _self
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
# layout:
#   Calendar:
#     style: column
#     icon: mdi-calendar
#     initiallyCollapsed: false
#   Administration:
#     style: column
#     columns: 5
#     icon: mdi-network
#   Monitoring:
#     style: column
#     columns: 5
#     icon: grafana.png
#   Storage:
#     style: column
#     columns: 5
#     icon: synology.png
#   Media:
#     style: column
#     columns: 5
#     icon: mdi-download-circle
