---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./hoarder/ks.yaml
  - ./miniflux/ks.yaml
  - ./onlyoffice/ks.yaml
  - ./paperless/ks.yaml
  - ./rsshub/ks.yaml
  - ./signal-cli/ks.yaml
  - ./n8n/ks.yaml
  - ./home-assistant/ks.yaml
  - ./glance/ks.yaml
  - ./tandoor/ks.yaml
  - ./nextcloud/ks.yaml
  - ./memos/ks.yaml
  - ./minio/ks.yaml
  - ./smtp-relay/ks.yaml
