# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app stalwart
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      stalwart:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.6.0@sha256:86a1992d46273c58fd4ad95b626081dfaabfe16bd56944675169e406d1a660dd
            envFrom: &env
              - secretRef:
                  name: stalwart-secret
        containers:
          app:
            image:
              repository: ghcr.io/stalwartlabs/stalwart
              tag: v0.14.1-alpine
            envFrom: *env
    service:
      app:
        controller: *app
        ports:
          https:
            port: 443
          http:
            port: 8080
          jmap:
            port: 8111
          smtp:
            port: 25
          smtps:
            port: 465
          imaps:
            port: 993
          sieve:
            port: 4190
    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          stalwart:
            app:
              - path: /opt/stalwart
      config:
        type: configMap
        name: stalwart-configmap
        advancedMounts:
          stalwart:
            app:
              - path: /opt/stalwart/etc/config.toml
                subPath: config.toml
      certificate:
        type: secret
        name: stalwart-tls
        advancedMounts:
          stalwart:
            app:
              - path: /etc/stalwart/live/${SECRET_DOMAIN}/
