---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stalwart
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  hostnames:
    - mail.${SECRET_DOMAIN}
    - mta-sts.${SECRET_DOMAIN}
    - autodiscover.${SECRET_DOMAIN}
    - autoconfig.${SECRET_DOMAIN}
  rules:
    - backendRefs:
        - name: stalwart
          port: 8080
