---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./hr.yaml
  - ./httproute.yaml
  - ./tcproute.yaml
  - ./certificate.yaml
  - ./es.yaml
  - ../../../../components/volsync/
configMapGenerator:
  - name: stalwart-configmap
    files:
      - config.toml=./config/config.toml
generatorOptions:
  disableNameSuffixHash: true
