---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: stalwart-smtp
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: smtp
  rules:
    - backendRefs:
        - name: stalwart
          port: 25
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: stalwart-smtps
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: smtps
  rules:
    - backendRefs:
        - name: stalwart
          port: 465
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: stalwart-imaps
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: smtps
  rules:
    - backendRefs:
        - name: stalwart
          port: 993
