# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: adguard-dns-secret
stringData:
  ADGUARD_USER: ENC[AES256_GCM,data:0/TQQA==,iv:sEMNi3jteVL8zQ3Zg0xuR4TIcDjl4LXJmFDx9DcHCM4=,tag:vCX3D/HR9Jn3Mr9hktUB3A==,type:str]
  ADGUARD_PASSWORD: ENC[AES256_GCM,data:vbjIWnTJb52c+CPz,iv:2ydfIksLzXoSs/ok/VyEq1+foXfr2wHaBpNQj62WHQQ=,tag:ZSriL6fSU7vELNH1Gq6/ig==,type:str]
sops:
  age:
    - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiS3VwWjk1QTU1NzNHOS9B
        NCthRDZvQmNDdFlsaXFJRUNhVW9xSEUwK0hnCk5kZUpZWDNvUkNDSUJyRGRiRGx0
        d1ZVakFOTzlvYjBTK0VQNUNxSFo0dWcKLS0tIFhnRk4xYW03ZHRidFIrdDhjeG1U
        WGkzQ2N0M29KdnQ1NVJ1TVpPWWhDVDQKMvFuHKdiUBNeZbX4wu4QFDC2LZ4w3iql
        smC9KCKOdk7B2q0noIUsumZdytwFvKpFAXDBXZzZWL3HZVfMGHQlpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-02T13:38:48Z"
  mac: ENC[AES256_GCM,data:BRBnwNgjtGWOtuup8MJiPOz6RBeTwrvVQ3OJpi1mYK2QSKP3b7qg4cSoKh33WYsBfiBSxONY9EIaYVkaEhdRP06en+SOtP3nZEy8qLKAnMhyz0VzdlSYU9tTvx1ecjTg/Faq0RlVlnhGLthX6bTmQwTgWrcAoQ7z9qOm2oIMSMg=,iv:WOrea0gWuSQS9M7qe337aqTtKjvfFbC32NaeL8Wm940=,tag:4xBwe05USplVxJ7S4XT5dw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
