---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./rook-ceph.yaml
  - ./piraeus.yaml
  - ./backube.yaml
  - ./crunchy-userinit.yaml
  - ./node-feature-discovery.yaml
  - ./intel.yaml
  - ./grafana.yaml
  - ./nextcloud.yaml
  - ./tailscale.yaml
