---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: koito
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: koito-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        INIT_POSTGRES_DBNAME: koito
        INIT_POSTGRES_HOST: postgres16-rw.database.svc
        INIT_POSTGRES_USER: "{{ .DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .DATABASE_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .CNPG_password }}"
        KOITO_DATABASE_URL: "postgres://{{ .DATABASE_USER }}:{{ .DATABASE_PASSWORD }}@postgres16-rw.database.svc:5432/koito"
  dataFrom:
    - extract:
        key: Koito
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"
