---
# yaml-language-server: $schema=https://kubernetes-schemas.18b.haus/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo-init-db
  namespace: &namespace code
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: database
  path: ./kubernetes/apps/code/forgejo/init-db
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  force: true
  wait: true
  interval: 2h
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app forgejo
  namespace: &namespace code
spec:
  components:
    - ../../../../components/volsync/
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1h
  path: ./kubernetes/apps/code/forgejo/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - kind: ConfigMap
        name: cluster-settings
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
  dependsOn:
    - name: forgejo-init-db
      namespace: *namespace
    - name: external-secrets-stores
      namespace: external-secrets
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-runner
  namespace: &namespace code
spec:
  targetNamespace: *namespace
  path: ./kubernetes/apps/code/forgejo/runner
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: forgejo
      namespace: *namespace
  interval: 30m
  retryInterval: 1m
  timeout: 3m

