---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Warsaw"
  CLUSTER_CIDR: "10.69.0.0/16"
  NODE_CIDR: "10.0.0.0/16"
  NAS_ADDRESS: 10.0.2.3
  QBIT_ADDRESS: 10.0.255.250
  HA_GREEN_ADDRESS: 10.0.0.196
  NAS_BASE_URL: /mnt/core
  JELLYFIN_ADDRESS: 10.0.255.249
  POSTGRES_ADDRESS: 10.0.255.248
  CRUNCHY_PGO_ADDRESS: 10.0.255.247
  MINECRAFT_ADDRESS: 10.0.255.246
  SLSKD_ADDRESS: 10.0.255.245
  CLOUDNATIVE_PGO_ADDRESS: 10.0.255.244
  NAS_UID: "3001"
  NAS_GID: "3001"
